spring.application.name=BookInventoryMgmt
spring.datasource.url= jdbc:postgresql://localhost:5432/book
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8182

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
git